# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  metrics-port:
    type: string
    default: '10254'
    description: Metrics port
  webhook-port:
    type: string
    default: '443'
    description: Webhook port
